# Master Dictionary for WebUI of Murideo 8K Seven Generator
# commands should be formatted {function}||{category_type},{arg1},{arg2},{arg3},{arg4}
# function choices are SENDSINGLE, SENDDOUBLE, SENDOTHER
# id's are the args
# sometimes no args are sent
# TODO change keys to start at 0
# TODO keys that are titles currently should be changed to unique numbers
# TODO create documentation on the map in markdown

# TODO Figure out how to send 2 commands Timing/auto
# TODO Pattern/ire window
# TODO Add Pattern/hdr/12
# TODO Add Pattern/rgb triplet
# TODO Add Pattern/timing details

# TODO Figure out audio tests/sync-latency/av sensors functional test
# TODO Figure out audio tests/sync-latency/arm av latency
# TODO Figure out audio tests/sync-latency/arm arc latency
# TODO Figure out audio tests/sync-latency/arm earc latency

# TODO edid earc cds/sink device edid info/Handle EDID Return
# TODO edid/earc/ multiple category commands needed
# TODO arc hpd ctl & arc physical hpd ctl seem to use same commands??

# TODO send cec command requires different logic
# TODO system/ip figure out commands for configuring ip
# TODO vitals/returns a bunch of values
# TODO fan control high and medium seem the same?
# TODO tools buttons READ & WRITE
# TODO Update Firmware opens file dialog
# TODO Reboot can't find command


murideo = {
    "video generator": {
        "tag": "Video Generator",
        "timing": {
            "tag": "TIMING",
            "function": "sendsingle",
            "category_type": 97,
            "8k": {
                "tag": "8K",
                "7680x4320@30": {
                    "id": 110,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 30,
                    "tag": "7680x4320 30Hz",
                },
                "7680x4320@29.97": {
                    "id": 111,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 29.97,
                    "tag": "7680x4320 29.97Hz",
                },
                "7680x4320@25": {
                    "id": 112,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 25,
                    "tag": "7680x4320 25Hz",
                },
                "7680x4320@24": {
                    "id": 113,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 24,
                    "tag": "7680x4320 24Hz",
                },
                "7680x4320@23.98": {
                    "id": 114,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 23.98,
                    "tag": "7680x4320 23.98Hz",
                },
                "7680x4320@60": {
                    "id": 115,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 60,
                    "tag": "7680x4320 60Hz",
                },
                "7680x4320@59.94": {
                    "id": 116,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 59.94,
                    "tag": "7680x4320 59.94Hz",
                },
                "7680x4320@50": {
                    "id": 117,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 50,
                    "tag": "7680x4320 50Hz",
                },
                "7680x4320@48": {
                    "id": 118,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 48,
                    "tag": "7680x4320 48Hz",
                },
                "7680x4320@47.95": {
                    "id": 119,
                    "h_rez": 7680,
                    "v_rez": 4320,
                    "refresh": 47.95,
                    "tag": "7680x4320 47.95Hz",
                },
            },
            "uhd": {
                "tag": "UHD",
                "3840x2160@30": {
                    "id": 28,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 30,
                    "tag": "3840x2160 30Hz",
                },
                "3840x2160@29.97": {
                    "id": 29,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 29.97,
                    "tag": "3840x2160 29.97Hz",
                },
                "3840x2160@25": {
                    "id": 30,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 25,
                    "tag": "3840x2160 25Hz",
                },
                "3840x2160@24": {
                    "id": 31,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 24,
                    "tag": "3840x2160 24Hz",
                },
                "3840x2160@23.98": {
                    "id": 32,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 23.98,
                    "tag": "3840x2160 23.98Hz",
                },
                "3840x2160@60": {
                    "id": 34,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 60,
                    "tag": "3840x2160 60Hz",
                },
                "3840x2160@59.94": {
                    "id": 35,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 59.94,
                    "tag": "3840x2160 59.94Hz",
                },
                "3840x2160@50": {
                    "id": 36,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 50,
                    "tag": "3840x2160 50Hz",
                },
                "3840x2160@48": {
                    "id": 103,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 48,
                    "tag": "3840x2160 48Hz",
                },
                "3840x2160@47.95": {
                    "id": 104,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 47.95,
                    "tag": "3840x2160 47.95Hz",
                },
                "3840x2160@100": {
                    "id": 107,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 100,
                    "tag": "3840x2160 100Hz",
                },
                "3840x2160@120": {
                    "id": 108,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 120,
                    "tag": "3840x2160 120Hz",
                },
                "3840x2160@119.88": {
                    "id": 109,
                    "h_rez": 3840,
                    "v_rez": 2160,
                    "refresh": 119.88,
                    "tag": "3840x2160 119.88Hz",
                },
            },
            "4k-dci": {
                "tag": "4K-DCI",
                "4096x2160@30": {
                    "id": 53,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 30,
                    "tag": "4096x2160 30Hz",
                },
                "4096x2160@29.97": {
                    "id": 54,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 29.97,
                    "tag": "4096x2160 29.97Hz",
                },
                "4096x2160@25": {
                    "id": 55,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 25,
                    "tag": "4096x2160 25Hz",
                },
                "4096x2160@24": {
                    "id": 44,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 24,
                    "tag": "4096x2160 24Hz",
                },
                "4096x2160@23.976": {
                    "id": 56,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 23.976,
                    "tag": "4096x2160 23.976Hz",
                },
                "4096x2160@60": {
                    "id": 57,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 60,
                    "tag": "4096x2160 60Hz",
                },
                "4096x2160@59.94": {
                    "id": 58,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 59.94,
                    "tag": "4096x2160 59.94Hz",
                },
                "4096x2160@50": {
                    "id": 59,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 50,
                    "tag": "4096x2160 50Hz",
                },
                "4096x2160@48": {
                    "id": 105,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 48,
                    "tag": "4096x2160 48Hz",
                },
                "4096x2160@47.95": {
                    "id": 106,
                    "h_rez": 4096,
                    "v_rez": 2160,
                    "refresh": 47.95,
                    "tag": "4096x2160 47.95Hz",
                },
            },
            "2k-dci": {
                "tag": "2K-DCI",
                "2048x1080@30": {
                    "id": 73,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 30,
                    "tag": "2048x1080 30Hz",
                },
                "2048x1080@29.97": {
                    "id": 74,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 29.97,
                    "tag": "2048x1080 29.97Hz",
                },
                "2048x1080@25": {
                    "id": 75,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 25,
                    "tag": "2048x1080 25Hz",
                },
                "2048x1080@24": {
                    "id": 76,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 24,
                    "tag": "2048x1080 24Hz",
                },
                "2048x1080@23.976": {
                    "id": 77,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 23.976,
                    "tag": "2048x1080 23.976Hz",
                },
                "2048x1080@60": {
                    "id": 78,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 60,
                    "tag": "2048x1080 60Hz",
                },
                "2048x1080@59.94": {
                    "id": 79,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 59.94,
                    "tag": "2048x1080 59.94Hz",
                },
                "2048x1080@50": {
                    "id": 80,
                    "h_rez": 2048,
                    "v_rez": 1080,
                    "refresh": 50,
                    "tag": "2048x1080 50Hz",
                },
            },
            "hd": {
                "tag": "HD",
                "1280x720p@60": {
                    "id": 12,
                    "h_rez": 1280,
                    "v_rez": 720,
                    "refresh": 60,
                    "tag": "720P 60Hz",
                },
                "1280x720p@59.94": {
                    "id": 13,
                    "h_rez": 1280,
                    "v_rez": 720,
                    "refresh": 59.94,
                    "tag": "720P 59.94Hz",
                },
                "1920x1080i@60": {
                    "id": 14,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 60,
                    "tag": "1080i 60Hz",
                },
                "1920x1080i@59.94": {
                    "id": 15,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 59.94,
                    "tag": "1080i 59.94Hz",
                },
                "1920x1080p@30": {
                    "id": 16,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 30,
                    "tag": "1080p 30Hz",
                },
                "1920x1080p@29.97": {
                    "id": 17,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 29.97,
                    "tag": "1080p 29.97Hz",
                },
                "1920x1080p@24": {
                    "id": 18,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 24,
                    "tag": "1080p 24Hz",
                },
                "1920x1080p@23.976": {
                    "id": 19,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 23.976,
                    "tag": "1080p 23.976Hz",
                },
                "1920x1080p@60": {
                    "id": 20,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 60,
                    "tag": "1080p 60Hz",
                },
                "1920x1080p@59.94": {
                    "id": 21,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 59.94,
                    "tag": "1080p 59.94Hz",
                },
                "1280x720p@50": {
                    "id": 24,
                    "h_rez": 1280,
                    "v_rez": 720,
                    "refresh": 50,
                    "tag": "720P 50Hz",
                },
                "1920x1080i@50": {
                    "id": 25,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 50,
                    "tag": "1080i 50Hz",
                },
                "1920x1080p@25": {
                    "id": 26,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 25,
                    "tag": "1080p 25Hz",
                },
                "1920x1080p@50": {
                    "id": 27,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 50,
                    "tag": "1080p 50Hz",
                },
                "1920x1080p@120": {
                    "id": 81,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 120,
                    "tag": "1080p 120Hz",
                },
                "1920x1080p@119.88": {
                    "id": 82,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 119.88,
                    "tag": "1080p 119.88Hz",
                },
                "1920x1080p@100": {
                    "id": 102,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 100,
                    "tag": "1080p 100Hz",
                },
            },
            "sd": {
                "tag": "SD",
                "720x480i@59.94": {
                    "id": 10,
                    "h_rez": 720,
                    "v_rez": 480,
                    "refresh": 59.94,
                    "tag": "480i 59.94Hz",
                },
                "720x480p@59.94": {
                    "id": 11,
                    "h_rez": 720,
                    "v_rez": 480,
                    "refresh": 59.94,
                    "tag": "480p 59.94Hz",
                },
                "720x576i@50": {
                    "id": 22,
                    "h_rez": 720,
                    "v_rez": 576,
                    "refresh": 50,
                    "tag": "576i 50Hz",
                },
                "720x576p@50": {
                    "id": 23,
                    "h_rez": 720,
                    "v_rez": 576,
                    "refresh": 50,
                    "tag": "576p 50Hz",
                },
            },
            "vesa": {
                "tag": "VESA",
                "640x480@60": {
                    "id": 0,
                    "h_rez": 640,
                    "v_rez": 480,
                    "refresh": 60,
                    "tag": "VGA 640x480",
                },
                "800x600@60": {
                    "id": 1,
                    "h_rez": 800,
                    "v_rez": 600,
                    "refresh": 60,
                    "tag": "SVGA 800x600",
                },
                "1024x768@60": {
                    "id": 2,
                    "h_rez": 1024,
                    "v_rez": 768,
                    "refresh": 60,
                    "tag": "XGA 1024x768",
                },
                "1152x864@60": {
                    "id": 72,
                    "h_rez": 1152,
                    "v_rez": 864,
                    "refresh": 60,
                    "tag": "XGA+ 1152x864",
                },
                "1360x768@60": {
                    "id": 4,
                    "h_rez": 1360,
                    "v_rez": 768,
                    "refresh": 60,
                    "tag": "HD 1360x768",
                },
                "1280x768@60": {
                    "id": 3,
                    "h_rez": 1280,
                    "v_rez": 768,
                    "refresh": 60,
                    "tag": "HD 1280x768",
                },
                "1280x960@60": {
                    "id": 5,
                    "h_rez": 1280,
                    "v_rez": 896064,
                    "refresh": 60,
                    "tag": "SXGA 1280x960",
                },
                "1400x1050@60": {
                    "id": 7,
                    "h_rez": 1400,
                    "v_rez": 1050,
                    "refresh": 60,
                    "tag": "SXGA+ 1400x1050",
                },
                "1440x900@60": {
                    "id": 69,
                    "h_rez": 1440,
                    "v_rez": 60,
                    "refresh": 60,
                    "tag": "WXGA+ 1440x900",
                },
                "1600x900@60": {
                    "id": 70,
                    "h_rez": 1600,
                    "v_rez": 900,
                    "refresh": 60,
                    "tag": "HD+ 1600x900",
                },
                "1600x1200@60": {
                    "id": 8,
                    "h_rez": 1600,
                    "v_rez": 1200,
                    "refresh": 60,
                    "tag": "UXGA 1600x1200",
                },
                "1920x1200@60": {
                    "id": 9,
                    "h_rez": 1920,
                    "v_rez": 1200,
                    "refresh": 60,
                    "tag": "WUXGA 1920x1200",
                },
                "1152x900@60": {
                    "id": 83,
                    "h_rez": 1152,
                    "v_rez": 900,
                    "refresh": 60,
                    "tag": "XGA+ 1152x900",
                },
                "1280x800@60": {
                    "id": 84,
                    "h_rez": 1280,
                    "v_rez": 800,
                    "refresh": 60,
                    "tag": "WXGA 1280x800",
                },
                "1280x1050@60": {
                    "id": 85,
                    "h_rez": 1280,
                    "v_rez": 1050,
                    "refresh": 60,
                    "tag": "SXGA 1280x1050",
                },
                "1920x1280@60": {
                    "id": 86,
                    "h_rez": 1920,
                    "v_rez": 1280,
                    "refresh": 60,
                    "tag": "UN 1920x1280",
                },
                "1920x1440@60": {
                    "id": 87,
                    "h_rez": 1920,
                    "v_rez": 1440,
                    "refresh": 60,
                    "tag": "UN 1920x1440",
                },
                "2048x1152@60": {
                    "id": 88,
                    "h_rez": 2048,
                    "v_rez": 1152,
                    "refresh": 60,
                    "tag": "QWXGA 2048x1152",
                },
                "2048x1536@60": {
                    "id": 89,
                    "h_rez": 2048,
                    "v_rez": 1536,
                    "refresh": 60,
                    "tag": "QXGA 2048x1536",
                },
                "2160x1440@60": {
                    "id": 90,
                    "h_rez": 2160,
                    "v_rez": 1440,
                    "refresh": 60,
                    "tag": "UN 2160x1440",
                },
                "2560x1080@60": {
                    "id": 91,
                    "h_rez": 2560,
                    "v_rez": 1080,
                    "refresh": 60,
                    "tag": "UN 2560x1080",
                },
                "2560x1440@60": {
                    "id": 92,
                    "h_rez": 2560,
                    "v_rez": 1440,
                    "refresh": 60,
                    "tag": "QHD 2560x1440",
                },
                "2560x1600@60": {
                    "id": 93,
                    "h_rez": 2560,
                    "v_rez": 1600,
                    "refresh": 60,
                    "tag": "WQXGA 2560x1600",
                },
                "2560x2048@60": {
                    "id": 94,
                    "h_rez": 2560,
                    "v_rez": 2048,
                    "refresh": 60,
                    "tag": "QSXGA 2560x2048",
                },
                "2880x1800@60": {
                    "id": 95,
                    "h_rez": 2880,
                    "v_rez": 1800,
                    "refresh": 60,
                    "tag": "QWXGA+ 2880x1800",
                },
                "2960x1440@60": {
                    "id": 96,
                    "h_rez": 2960,
                    "v_rez": 1440,
                    "refresh": 60,
                    "tag": "GAL 2960x1440",
                },
                "3000x2000@60": {
                    "id": 97,
                    "h_rez": 3000,
                    "v_rez": 2000,
                    "refresh": 60,
                    "tag": "SUR 3000x2000",
                },
                "3200x2048@60": {
                    "id": 98,
                    "h_rez": 3200,
                    "v_rez": 2048,
                    "refresh": 60,
                    "tag": "WQSXGA 3200x2048",
                },
                "3440x1440@60": {
                    "id": 99,
                    "h_rez": 3440,
                    "v_rez": 1440,
                    "refresh": 60,
                    "tag": "UWQHD 3440X1440",
                },
                "3840x1600@60": {
                    "id": 72,
                    "h_rez": 3840,
                    "v_rez": 1600,
                    "refresh": 60,
                    "tag": "UW4K 3840x1600",
                },
                "3840x2400@60": {
                    "id": 101,
                    "h_rez": 3840,
                    "v_rez": 2400,
                    "refresh": 60,
                    "tag": "WQUXGA 3840x2400",
                },
            },
            "3d": {
                "tag": "3D",
                "1280x720p@60": {
                    "id": 37,
                    "h_rez": 1280,
                    "v_rez": 720,
                    "refresh": 60,
                    "tag": "720P 60Hz (3D-FP)",
                },
                "1280x720p@59.94": {
                    "id": 38,
                    "h_rez": 1280,
                    "v_rez": 720,
                    "refresh": 59.94,
                    "tag": "720P 59.94Hz (3D-FP)",
                },
                "1920x1080p@24": {
                    "id": 39,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 24,
                    "tag": "1080P 24Hz (3D-FP)",
                },
                "1920x1080P@23.976": {
                    "id": 40,
                    "h_rez": 1920,
                    "v_rez": 1080,
                    "refresh": 23.976,
                    "tag": "1080P 23.976Hz (3D-FP)",
                },
                "1280x720p@50": {
                    "id": 41,
                    "h_rez": 1280,
                    "v_rez": 720,
                    "refresh": 50,
                    "tag": "720P 50Hz (3D-FP)",
                },
            },
            "custom": {
                "tag": "CUSTOM",
                "USER-1": {
                    "id": 43,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-1",
                },
                "USER-2": {
                    "id": 44,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-2",
                },
                "USER-3": {
                    "id": 45,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-3",
                },
                "USER-4": {
                    "id": 46,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-4",
                },
                "USER-5": {
                    "id": 47,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-5",
                },
                "USER-6": {
                    "id": 48,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-6",
                },
                "USER-7": {
                    "id": 49,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-9",
                },
                "USER-8": {
                    "id": 50,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-8",
                },
                "USER-9": {
                    "id": 51,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-9",
                },
                "USER-10": {
                    "id": 52,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "USER-10",
                },
            },
            "auto": {
                "tag": "AUTO",
                "AUTO": {
                    "id": 43,
                    "h_rez": None,
                    "v_rez": None,
                    "refresh": None,
                    "tag": "Auto(Output timing based on EDID of sink device)",
                },
            },
        },
        "pattern": {
            "tag": "PATTERN",
            "function": "senddouble",
            "category_type": 98,
            "fpga": {
                "tag": "FPGA",
                0: {"id": 0, "tag": "100% Color Bars"},
                1: {"id": 1, "tag": "75% Color Bars"},
                2: {"id": 2, "tag": "8 Step Gray Bars"},
                3: {"id": 3, "tag": "16 Step Gray Bars"},
                4: {"id": 4, "tag": "Red Screen"},
                5: {"id": 5, "tag": "Green Screen"},
                6: {"id": 6, "tag": "Blue Screen"},
                7: {"id": 7, "tag": "Cyan Screen"},
                8: {"id": 8, "tag": "Magenta Screen"},
                9: {"id": 9, "tag": "Yellow Screen"},
                10: {"id": 10, "tag": "Black Screen"},
                11: {"id": 11, "tag": "White Screen"},
                12: {"id": 12, "tag": "Vertical Split"},
                13: {"id": 13, "tag": "Horizontal Split"},
                14: {"id": 14, "tag": "Multiburst Vert."},
                15: {"id": 15, "tag": "Multiburst Hor."},
                16: {"id": 16, "tag": "Quarter Block 1"},
                17: {"id": 17, "tag": "Quarter Block 2"},
                18: {"id": 18, "tag": "Alternate W.B"},
                19: {"id": 19, "tag": "RGB CMY Ramps"},
                20: {"id": 20, "tag": "Black Pluge"},
                21: {"id": 21, "tag": "White Pluge"},
                22: {"id": 22, "tag": "Still Gray Ramp 1"},
                23: {"id": 23, "tag": "Still gray Ramp 2"},
                24: {"id": 24, "tag": "Smpte Bars"},
                25: {"id": 25, "tag": "Border Lines"},
                26: {"id": 26, "tag": "Window"},
                27: {"id": 27, "tag": "3D Boxes"},
                28: {"id": 28, "tag": "Line V.Scroll"},
                29: {"id": 29, "tag": "Line H.Scroll"},
                30: {"id": 30, "tag": "A/V Sync"},
                31: {"id": 31, "tag": "Gray Ramp"},
                32: {"id": 32, "tag": "Red Ramp"},
                33: {"id": 33, "tag": "Green Ramp"},
                34: {"id": 34, "tag": "Blue Ramp"},
                35: {"id": 35, "tag": "Moving Ball"},
            },
            "isf": {
                "tag": "ISF",
                0: {"id": 36, "tag": "White Pluge UHD"},
                1: {"id": 37, "tag": "Black Pluge UHD"},
                2: {"id": 38, "tag": "Geometry UHD"},
                3: {"id": 39, "tag": "White Pluge HD"},
                4: {"id": 40, "tag": "Black Pluge HD"},
                5: {"id": 41, "tag": "Geometry 178 HD"},
                6: {"id": 42, "tag": "Geometry 240 HD"},
                7: {"id": 43, "tag": "ISF Color Girls"},
                8: {"id": 44, "tag": "PD Family"},
                9: {"id": 45, "tag": "Red Blue MTB"},
                10: {"id": 46, "tag": "Cone Gradiant"},
                11: {"id": 47, "tag": "ISF Dog"},
            },
            "dvs hdr": {
                "tag": "DVS HDR",
                "clipping & color": {
                    "tag": "CLIPPING & COLOR",
                    0: {"id": 48, "tag": "Black Level 1"},
                    1: {"id": 49, "tag": "Black Level 2"},
                    2: {"id": 50, "tag": "White Level 1"},
                    3: {"id": 51, "tag": "White Level 2"},
                    4: {"id": 52, "tag": "White Level 3"},
                    5: {"id": 53, "tag": "White 80-100"},
                    6: {"id": 54, "tag": "HDR Mix"},
                    7: {"id": 55, "tag": "HDR Greyscale"},
                    8: {"id": 56, "tag": "HDR Red"},
                    9: {"id": 57, "tag": "HDR Green"},
                    10: {"id": 58, "tag": "HDR Blue"},
                    11: {"id": 59, "tag": "HDR Yellow"},
                    12: {"id": 60, "tag": "HDR Cyan"},
                    13: {"id": 61, "tag": "HDR Magenta"},
                    14: {"id": 62, "tag": "Multi-Cube"},
                    15: {"id": 63, "tag": "10 Patch Mix"},
                    16: {"id": 64, "tag": "Greyscale 1000"},
                    17: {"id": 65, "tag": "Greyscale 2000"},
                    18: {"id": 66, "tag": "Greyscale 4000"},
                    19: {"id": 67, "tag": "Greyscale 10000"},
                    20: {"id": 68, "tag": "Color High"},
                    21: {"id": 69, "tag": "Color Low"},
                    22: {"id": 70, "tag": "Decoding 50%"},
                    23: {"id": 71, "tag": "Decoding 100%"},
                    24: {"id": 72, "tag": "Blue Filter 100%"},
                    25: {"id": 73, "tag": "Green Filter 100%"},
                    26: {"id": 74, "tag": "Red Filter 100%"},
                    27: {"id": 75, "tag": "Blue Filter 50%"},
                    28: {"id": 76, "tag": "Green Filter 50%"},
                    29: {"id": 77, "tag": "Red Filter 50%"},
                    30: {"id": 78, "tag": "Color Flashing"},
                    31: {"id": 79, "tag": "Dynamic Contrast"},
                },
                "evaluation": {
                    "tag": "EVALUATION",
                    0: {"id": 80, "tag": "Landscape"},
                    1: {"id": 81, "tag": "Skin Tone"},
                    2: {"id": 82, "tag": "Skin Tone"},
                    3: {"id": 83, "tag": "City Sunset"},
                    4: {"id": 84, "tag": "Oceanside"},
                    5: {"id": 85, "tag": "Pantone Skin"},
                    6: {"id": 86, "tag": "Restaurant"},
                    7: {"id": 87, "tag": "Indian Market"},
                    8: {"id": 88, "tag": "Ambient 05 Nit"},
                    9: {"id": 89, "tag": "Ambient 10 Nit"},
                    10: {"id": 90, "tag": "Ambient 15 Nit"},
                    11: {"id": 91, "tag": "Chroma Sub 100"},
                    12: {"id": 92, "tag": "Chroma Sub 500"},
                    13: {"id": 93, "tag": "Chroma Sub 1000"},
                    14: {"id": 94, "tag": "Judder 24 FPS"},
                    15: {"id": 95, "tag": "Judder 60 FPS"},
                    16: {"id": 96, "tag": "M Judder 24 FPS"},
                },
                "geometry & convergence": {
                    "tag": "GEOMETRY & CONVERGENCE",
                    0: {"id": 97, "tag": "Apsect Ratio 1.78"},
                    1: {"id": 98, "tag": "Apsect Ratio 1.85"},
                    2: {"id": 99, "tag": "Apsect Ratio 2.00"},
                    3: {"id": 100, "tag": "Apsect Ratio 2.35"},
                    4: {"id": 101, "tag": "Apsect Ratio 2.40"},
                    5: {"id": 102, "tag": "Apsect Ratio All"},
                    6: {"id": 103, "tag": "Grid White"},
                    7: {"id": 104, "tag": "Grid Red"},
                    8: {"id": 105, "tag": "Grid Green"},
                    9: {"id": 106, "tag": "Grid Blue"},
                    10: {"id": 107, "tag": "Grid Yellow"},
                    11: {"id": 108, "tag": "Grid Cyan"},
                    12: {"id": 109, "tag": "Grid Magenta"},
                    13: {"id": 110, "tag": "Dot White"},
                    14: {"id": 111, "tag": "Dot Red"},
                    15: {"id": 112, "tag": "Dot Green"},
                    16: {"id": 113, "tag": "Dot Blue"},
                    17: {"id": 114, "tag": "Dot Yellow"},
                    18: {"id": 115, "tag": "Dot Cyan"},
                    19: {"id": 116, "tag": "Dot Magenta"},
                    20: {"id": 117, "tag": "Cross White"},
                    21: {"id": 118, "tag": "Cross Red"},
                    22: {"id": 119, "tag": "Cross Green"},
                    23: {"id": 120, "tag": "Cross Blue"},
                    24: {"id": 121, "tag": "Cross Yellow"},
                    25: {"id": 122, "tag": "Cross Cyan"},
                    26: {"id": 123, "tag": "Cross Magenta"},
                },
                "ramps, gradients, zone plates": {
                    "tag": "RAMPS,GRADIENTS,ZONE PLATES",
                    0: {"id": 124, "tag": "Greyscale Steps"},
                    1: {"id": 125, "tag": "Greyscale Ramp"},
                    2: {"id": 126, "tag": "Greyscale Mix"},
                    3: {"id": 127, "tag": "Color Steps"},
                    4: {"id": 128, "tag": "Color Ramp"},
                    5: {"id": 129, "tag": "Color Ramp H&V"},
                    6: {"id": 130, "tag": "Color Ramp Mix"},
                    7: {"id": 131, "tag": "Color Bar Ramp"},
                    8: {"id": 132, "tag": "Ramp Red"},
                    9: {"id": 133, "tag": "Ramp Green"},
                    10: {"id": 134, "tag": "Ramp Blue"},
                    11: {"id": 135, "tag": "Ramp Yellow"},
                    12: {"id": 136, "tag": "Ramp Cyan"},
                    13: {"id": 137, "tag": "Ramp Magenta"},
                    14: {"id": 138, "tag": "Zone White"},
                    15: {"id": 139, "tag": "Zone Red"},
                    16: {"id": 140, "tag": "Zone Green"},
                    17: {"id": 141, "tag": "Zone Blue"},
                    18: {"id": 142, "tag": "Zone Magenta"},
                    19: {"id": 143, "tag": "Zone Yellow"},
                    20: {"id": 144, "tag": "Zone Cyan"},
                    21: {"id": 145, "tag": "Radial Grey"},
                    22: {"id": 146, "tag": "Radial Red"},
                    23: {"id": 147, "tag": "Radial Green"},
                    24: {"id": 148, "tag": "Radial Blue"},
                    25: {"id": 149, "tag": "Radial Yellow"},
                    26: {"id": 150, "tag": "Radial Cyan"},
                    27: {"id": 151, "tag": "Radial Magenta"},
                },
                "resolution, ansi, placement": {
                    "tag": "RESOLUTION,ANSI,PLACEMENT",
                    0: {"id": 152, "tag": "Resolution Mix"},
                    1: {"id": 153, "tag": "Checkerboard"},
                    2: {"id": 154, "tag": "Horizontal 1px"},
                    3: {"id": 155, "tag": "Horizontal 2px"},
                    4: {"id": 156, "tag": "Horizontal 3px"},
                    5: {"id": 157, "tag": "Vertical 1px"},
                    6: {"id": 158, "tag": "Vertical 2px"},
                    7: {"id": 159, "tag": "Vertical 3px"},
                    8: {"id": 160, "tag": "Black Pixels"},
                    9: {"id": 161, "tag": "ANSI Meter 8x8"},
                    10: {"id": 162, "tag": "ANSI 8x8"},
                    11: {"id": 163, "tag": "ANSI Meter 5x4"},
                    12: {"id": 164, "tag": "ANSI M5x4 Black"},
                    13: {"id": 165, "tag": "ANSI M5x4 White"},
                    14: {"id": 166, "tag": "Meter Placement"},
                    15: {"id": 167, "tag": "Sharp & Scan"},
                },
            },
            "dvs dolby vision": {
                "tag": "DVS Dolby Vision",
                "clipping & color": {
                    "tag": "CLIPPING & COLOR",
                    0: {"id": 472, "tag": "Black Level 1"},
                    1: {"id": 473, "tag": "Black Level 2"},
                    2: {"id": 474, "tag": "White Level 1"},
                    3: {"id": 475, "tag": "White Level 2"},
                    4: {"id": 476, "tag": "White Level 3"},
                    5: {"id": 477, "tag": "White 80-100"},
                    6: {"id": 478, "tag": "Blue Filter 50%"},
                    7: {"id": 479, "tag": "Green Filter 50%"},
                    8: {"id": 480, "tag": "Red Filter 50%"},
                    9: {"id": 481, "tag": "Color Clipping High"},
                    10: {"id": 482, "tag": "Color Clipping Low"},
                    11: {"id": 483, "tag": "Color Decoding"},
                    12: {"id": 484, "tag": "Color Flashing"},
                },
                "evaluation": {
                    "tag": "EVALUATION",
                    0: {"id": 485, "tag": "Landscape"},
                    1: {"id": 486, "tag": "Nature"},
                    2: {"id": 487, "tag": "Skin Tone"},
                    3: {"id": 488, "tag": "City Sunset"},
                    4: {"id": 489, "tag": "Oceanside"},
                    5: {"id": 490, "tag": "Pantone Skin"},
                    6: {"id": 491, "tag": "Restaurant"},
                    7: {"id": 492, "tag": "Indian Market"},
                },
                "ramps, gradients, zone plates": {
                    "tag": "RAMPS,GRADIENTS,ZONE PLATES",
                    0: {"id": 493, "tag": "Greyscale Steps"},
                    1: {"id": 494, "tag": "Greyscale Ramp"},
                    2: {"id": 495, "tag": "Greyscale Mix"},
                    3: {"id": 496, "tag": "Color Steps"},
                    4: {"id": 497, "tag": "Red Radial Gradient"},
                    5: {"id": 498, "tag": "Green Radial Gradient"},
                    6: {"id": 499, "tag": "Blue Radial Gradient"},
                    7: {"id": 500, "tag": "Yellow Radial Gradient"},
                    8: {"id": 501, "tag": "Cyan Radial Gradient"},
                    9: {"id": 502, "tag": "Magenta Radial Gradient"},
                },
                "resolution, ansi, placement": {
                    "tag": "RESOLUTION,ANSI,PLACEMENT",
                    0: {"id": 503, "tag": "ANSI Meter 8x8"},
                    1: {"id": 504, "tag": "ANSI 8x8 Black"},
                    2: {"id": 505, "tag": "ANSI 8x8 White"},
                    3: {"id": 506, "tag": "ANSI Meter 5x4"},
                    4: {"id": 507, "tag": "ANSI M5x4 Black"},
                    5: {"id": 508, "tag": "ANSI M5x4 White"},
                    6: {"id": 509, "tag": "Meter Placement"},
                    7: {"id": 510, "tag": "Sharp & Scan"},
                },
            },
            "dvs hlg": {
                "tag": "DVS HLG",
                "clipping & color": {
                    "tag": "CLIPPING & COLOR",
                    0: {"id": 511, "tag": "Black Level 1"},
                    1: {"id": 512, "tag": "Black Level 2"},
                    2: {"id": 513, "tag": "White Level 1"},
                    3: {"id": 514, "tag": "White Level 2"},
                    4: {"id": 515, "tag": "White Level 3"},
                    5: {"id": 517, "tag": "HDR Mix"},
                    6: {"id": 518, "tag": "HDR Greyscale"},
                    7: {"id": 519, "tag": "HDR Red"},
                    8: {"id": 520, "tag": "HDR Green"},
                    9: {"id": 521, "tag": "HDR Blue"},
                    10: {"id": 522, "tag": "HDR Yellow"},
                    11: {"id": 523, "tag": "HDR Cyan"},
                    12: {"id": 524, "tag": "HDR Magenta"},
                    13: {"id": 525, "tag": "Multi-Cube"},
                    14: {"id": 526, "tag": "10 Patch Mix"},
                    15: {"id": 529, "tag": "Blue Filter 100%"},
                    16: {"id": 530, "tag": "Green Filter 100%"},
                    17: {"id": 531, "tag": "Red Filter 100%"},
                    18: {"id": 527, "tag": "Color Clipping High"},
                    19: {"id": 528, "tag": "Color Clipping Low"},
                    20: {"id": 532, "tag": "Color Decoding 50%"},
                    21: {"id": 533, "tag": "Color Decoding 100%"},
                    22: {"id": 516, "tag": "Color Flashing"},
                },
                "evaluation": {
                    "tag": "EVALUATION",
                    0: {"id": 534, "tag": "Landscape"},
                    1: {"id": 535, "tag": "Nature"},
                    2: {"id": 536, "tag": "Skin Tone"},
                    3: {"id": 537, "tag": "City Sunset"},
                    4: {"id": 538, "tag": "Oceanside"},
                    5: {"id": 539, "tag": "Pantone Skin"},
                    6: {"id": 540, "tag": "Restaurant"},
                    7: {"id": 541, "tag": "Indian Market"},
                },
                "ramps, gradients, zone plates": {
                    "tag": "RAMPS,GRADIENTS,ZONE PLATES",
                    0: {"id": 542, "tag": "Greyscale Steps"},
                    1: {"id": 543, "tag": "Greyscale Ramp"},
                    2: {"id": 544, "tag": "Greyscale Mix"},
                    3: {"id": 545, "tag": "Color Steps"},
                    4: {"id": 546, "tag": "Color Ramp"},
                    5: {"id": 547, "tag": "Color Ramp H&V"},
                    6: {"id": 548, "tag": "Color Ramp Mix"},
                    7: {"id": 549, "tag": "Color Bar Ramp"},
                    8: {"id": 550, "tag": "Ramp Red"},
                    9: {"id": 551, "tag": "Ramp Green"},
                    10: {"id": 552, "tag": "Ramp Blue"},
                    11: {"id": 553, "tag": "Ramp Yellow"},
                    12: {"id": 554, "tag": "Ramp Cyan"},
                    13: {"id": 555, "tag": "Ramp Magenta"},
                    14: {"id": 556, "tag": "Zone White"},
                    15: {"id": 557, "tag": "Zone Red"},
                    16: {"id": 558, "tag": "Zone Green"},
                    17: {"id": 559, "tag": "Zone Blue"},
                    18: {"id": 560, "tag": "Zone Magenta"},
                    19: {"id": 561, "tag": "Zone Yellow"},
                    20: {"id": 562, "tag": "Zone Cyan"},
                    21: {"id": 563, "tag": "Radial Grey"},
                    22: {"id": 564, "tag": "Radial Red"},
                    23: {"id": 565, "tag": "Radial Green"},
                    24: {"id": 566, "tag": "Radial Blue"},
                    25: {"id": 567, "tag": "Radial Yellow"},
                    26: {"id": 568, "tag": "Radial Cyan"},
                    27: {"id": 569, "tag": "Radial Magenta"},
                },
                "resolution, ansi, placement": {
                    "tag": "RESOLUTION,ANSI,PLACEMENT",
                    0: {"id": 570, "tag": "ANSI Meter 8x8"},
                    1: {"id": 571, "tag": "ANSI 8x8 Black"},
                    2: {"id": 572, "tag": "ANSI 8x8 White"},
                    3: {"id": 573, "tag": "ANSI Meter 5x4"},
                    4: {"id": 574, "tag": "ANSI M5x4 Black"},
                    5: {"id": 575, "tag": "ANSI M5x4 White"},
                    6: {"id": 576, "tag": "Meter Placement"},
                    7: {"id": 577, "tag": "Sharp & Scan"},
                    8: {"id": 578, "tag": "Resolution Mix"},
                },
            },
            "uhd sdr": {
                "tag": "UHD SDR",
                "clipping & gamma": {
                    "tag": "CLIPPING & GAMMA",
                    0: {"id": 168, "tag": "Target Limited"},
                    1: {"id": 169, "tag": "Target Full"},
                    2: {"id": 170, "tag": "Contrast Check"},
                    3: {"id": 171, "tag": "Contrast Lines"},
                    4: {"id": 172, "tag": "Gamma Check"},
                    5: {"id": 173, "tag": "Gamma Lines"},
                    6: {"id": 174, "tag": "High Clipping"},
                    7: {"id": 175, "tag": "High Clip Red"},
                    8: {"id": 176, "tag": "High Clip Green"},
                    9: {"id": 177, "tag": "High Clip Blue"},
                    10: {"id": 178, "tag": "Low Clipping"},
                    11: {"id": 179, "tag": "Low Clip Red"},
                    12: {"id": 180, "tag": "Low Clip Green"},
                    13: {"id": 181, "tag": "Low Clip Blue"},
                    14: {"id": 182, "tag": "Composite Grey"},
                    15: {"id": 183, "tag": "Composite Red"},
                    16: {"id": 184, "tag": "Composite Green"},
                    17: {"id": 185, "tag": "Composite Blue"},
                    18: {"id": 186, "tag": "Lin Step Grey"},
                    19: {"id": 187, "tag": "Lin Step Red"},
                    20: {"id": 188, "tag": "Lin Step Green"},
                    21: {"id": 189, "tag": "Lin Step Blue"},
                    22: {"id": 190, "tag": "Lin Step Magent"},
                    23: {"id": 191, "tag": "Lin Step Yellow"},
                    24: {"id": 192, "tag": "Lin Step Cyan"},
                    25: {"id": 193, "tag": "Log Step Grey"},
                    26: {"id": 194, "tag": "Log Step Red"},
                    27: {"id": 195, "tag": "Log Step Green"},
                    28: {"id": 196, "tag": "Log Step Blue"},
                    29: {"id": 197, "tag": "Log Step Magent"},
                    30: {"id": 198, "tag": "Log Step Yellow"},
                    31: {"id": 199, "tag": "Log Step Cyan"},
                    32: {"id": 200, "tag": "Gamma Grey"},
                    33: {"id": 201, "tag": "Gamma Red"},
                    34: {"id": 202, "tag": "Gamma Green"},
                    35: {"id": 203, "tag": "Gamma Blue"},
                    36: {"id": 204, "tag": "Gamma Lines Grey"},
                    37: {"id": 205, "tag": "Gamma Lines Red"},
                    38: {"id": 206, "tag": "Gamma Lines Green"},
                    39: {"id": 207, "tag": "Gamma Lines Blue"},
                },
                "color bars & noise": {
                    "tag": "COLOR BARS & NOISE",
                    0: {"id": 208, "tag": "Color Wipe Full"},
                    1: {"id": 209, "tag": "Color Wipe Half"},
                    2: {"id": 210, "tag": "Quick Check"},
                    3: {"id": 211, "tag": "H Bars RGB"},
                    4: {"id": 212, "tag": "H Bars RGBCMY"},
                    5: {"id": 214, "tag": "H Bars Shade"},
                    6: {"id": 215, "tag": "V Bars RGB"},
                    7: {"id": 216, "tag": "V Bars RGBCMY"},
                    8: {"id": 217, "tag": "V Bars Layover"},
                    9: {"id": 218, "tag": "V Bars Shade"},
                    10: {"id": 219, "tag": "Color Noise 01"},
                    11: {"id": 220, "tag": "Color Noise 02"},
                    12: {"id": 221, "tag": "Color Noise 04"},
                    13: {"id": 222, "tag": "Color Noise 08"},
                    14: {"id": 223, "tag": "Color Noise 16"},
                    15: {"id": 224, "tag": "Color Noise 01"},
                    16: {"id": 225, "tag": "Color Noise 02"},
                    17: {"id": 226, "tag": "Color Noise 04"},
                    18: {"id": 227, "tag": "Color Noise 08"},
                    19: {"id": 228, "tag": "Color Noise 16"},
                },
                "color checker": {
                    "tag": "COLOR CHECKER",
                    0: {"id": 229, "tag": "HSL BlueMagenta"},
                    1: {"id": 230, "tag": "HSL Blue"},
                    2: {"id": 231, "tag": "HSL Cyan Blue"},
                    3: {"id": 232, "tag": "HSL Cyan"},
                    4: {"id": 233, "tag": "HSL Green Cyan"},
                    5: {"id": 234, "tag": "HSL Green"},
                    6: {"id": 235, "tag": "HSL Magenta Red"},
                    7: {"id": 236, "tag": "HSL Magenta"},
                    8: {"id": 237, "tag": "HSL Red"},
                    9: {"id": 238, "tag": "HSL Yellow Green"},
                    10: {"id": 239, "tag": "HSL Yellow Red"},
                    11: {"id": 240, "tag": "HSL Yellow"},
                    12: {"id": 241, "tag": "HSV BlueMagenta"},
                    13: {"id": 243, "tag": "HSV Cyan Blue"},
                    14: {"id": 244, "tag": "HSV Cyan"},
                    15: {"id": 245, "tag": "HSV Green Cyan"},
                    16: {"id": 246, "tag": "HSV Green"},
                    17: {"id": 247, "tag": "HSV Magenta Red"},
                    18: {"id": 248, "tag": "HSV Magenta"},
                    19: {"id": 249, "tag": "HSV Red"},
                    20: {"id": 250, "tag": "HSV Yellow Green"},
                    21: {"id": 251, "tag": "HSV Yellow Red"},
                    22: {"id": 252, "tag": "HSV Yellow"},
                    23: {"id": 253, "tag": "RGB Blue 064"},
                    24: {"id": 254, "tag": "RGB Blue 127"},
                    25: {"id": 255, "tag": "RGB Blue 191"},
                    26: {"id": 256, "tag": "RGB Blue 255"},
                    27: {"id": 257, "tag": "RGB Green 064"},
                    28: {"id": 258, "tag": "RGB Green 127"},
                    29: {"id": 259, "tag": "RGB Green 191"},
                    30: {"id": 260, "tag": "RGB Green 255"},
                    31: {"id": 261, "tag": "RGB Red 064"},
                    32: {"id": 262, "tag": "RGB Red 127"},
                    33: {"id": 263, "tag": "RGB Red 191"},
                    34: {"id": 264, "tag": "RGB Red 255"},
                },
                "geometry and resolution": {
                    "tag": "GEOMETRY AND RESOLUTION",
                    0: {"id": 265, "tag": "H Convergence"},
                    1: {"id": 266, "tag": "V Convergence"},
                    2: {"id": 267, "tag": "H Length"},
                    3: {"id": 268, "tag": "V Length"},
                    4: {"id": 269, "tag": "Overscan"},
                    5: {"id": 270, "tag": "BW Evaluation"},
                    6: {"id": 271, "tag": "BW Evaluation 2"},
                    7: {"id": 272, "tag": "H Wedge"},
                    8: {"id": 273, "tag": "Star Burst"},
                    9: {"id": 274, "tag": "V Wedge"},
                    10: {"id": 275, "tag": "H Multiburst"},
                    11: {"id": 276, "tag": "V Multiburst"},
                    12: {"id": 277, "tag": "Checkers 02"},
                    13: {"id": 278, "tag": "Checkers 04"},
                    14: {"id": 279, "tag": "Checkers 08"},
                    15: {"id": 280, "tag": "Checkers 16"},
                    16: {"id": 281, "tag": "Checkers 32"},
                    17: {"id": 282, "tag": "Checkers Log"},
                    18: {"id": 283, "tag": "Many Circles"},
                    19: {"id": 284, "tag": "Center Circle"},
                    20: {"id": 285, "tag": "Many Squares"},
                    21: {"id": 286, "tag": "Grid"},
                    22: {"id": 287, "tag": "H Lines 02"},
                    23: {"id": 288, "tag": "H Lines 04"},
                    24: {"id": 289, "tag": "H Lines 08"},
                    25: {"id": 290, "tag": "H Lines Log"},
                    26: {"id": 291, "tag": "V Lines 02"},
                    27: {"id": 292, "tag": "V Lines 04"},
                    28: {"id": 293, "tag": "V Lines 08"},
                    29: {"id": 294, "tag": "V Lines Log"},
                    30: {"id": 295, "tag": "Points 02"},
                    31: {"id": 296, "tag": "Points 04"},
                    32: {"id": 297, "tag": "Points 08"},
                    33: {"id": 298, "tag": "Points 16"},
                    34: {"id": 299, "tag": "Points 32"},
                    35: {"id": 300, "tag": "Squares 02"},
                    36: {"id": 301, "tag": "Squares 04"},
                    37: {"id": 302, "tag": "Squares 08"},
                    38: {"id": 303, "tag": "Squares 16"},
                    39: {"id": 304, "tag": "Squares 32"},
                },
                "ramps": {
                    "tag": "RAMPS",
                    0: {"id": 305, "tag": "Color Patch"},
                    1: {"id": 306, "tag": "Triangle"},
                    2: {"id": 307, "tag": "Wireframe"},
                    3: {"id": 308, "tag": "Full Red"},
                    4: {"id": 309, "tag": "Full Green"},
                    5: {"id": 310, "tag": "Full Blue"},
                    6: {"id": 311, "tag": "Full Magenta"},
                    7: {"id": 312, "tag": "Full Yellow"},
                    8: {"id": 313, "tag": "Full Cyan"},
                    9: {"id": 314, "tag": "Full Grey"},
                    10: {"id": 315, "tag": "Half Red"},
                    11: {"id": 316, "tag": "Half Green"},
                    12: {"id": 317, "tag": "Half Blue"},
                    13: {"id": 318, "tag": "Half Magenta"},
                    14: {"id": 319, "tag": "Half Yellow"},
                    15: {"id": 320, "tag": "Half Cyan"},
                    16: {"id": 321, "tag": "HSL Sat 0.00"},
                    17: {"id": 322, "tag": "HSL Hue 0.00"},
                    18: {"id": 323, "tag": "HSL Hue 0.33"},
                    19: {"id": 324, "tag": "HSL Hue 0.66"},
                    20: {"id": 325, "tag": "HSL Lev 0.25"},
                    21: {"id": 326, "tag": "HSL Lev 0.50"},
                    22: {"id": 327, "tag": "HSL Lev 0.75"},
                    23: {"id": 328, "tag": "HSV Sat 0.00"},
                    24: {"id": 329, "tag": "HSV Sat 0.50"},
                    25: {"id": 330, "tag": "HSV Sat 1.00"},
                    26: {"id": 331, "tag": "HSV Hue 0.00"},
                    27: {"id": 332, "tag": "HSV Hue 0.33"},
                    28: {"id": 333, "tag": "HSV Hue 0.66"},
                    29: {"id": 334, "tag": "HSV Sat 0.50"},
                    30: {"id": 335, "tag": "HSV Sat 1.00"},
                    31: {"id": 336, "tag": "HSV Sat 0.00"},
                    32: {"id": 337, "tag": "HSV Sat 0.50"},
                    33: {"id": 338, "tag": "HSV Sat 1.00"},
                    34: {"id": 339, "tag": "RGB Green 000"},
                    35: {"id": 340, "tag": "RGB Green 127"},
                    36: {"id": 341, "tag": "RGB Green 255"},
                    37: {"id": 342, "tag": "RGB Blue 000"},
                    38: {"id": 343, "tag": "RGB Blue 127"},
                    39: {"id": 344, "tag": "RGB Blue 255"},
                    40: {"id": 345, "tag": "RGB Red 000"},
                    41: {"id": 346, "tag": "RGB Red 127"},
                    42: {"id": 347, "tag": "RGB Red 255"},
                },
            },
            "dolby vision": {
                "tag": "Dolby Vision",
                0: {"id": 425, "tag": "Dolby Vision UHD"},
                1: {"id": 426, "tag": "CornerBox_UHD"},
                2: {"id": 427, "tag": "Checker_UHD"},
                3: {"id": 428, "tag": "Steps_UHD_L255rm1"},
                4: {"id": 429, "tag": "Steps_UHD_L255rm2"},
                5: {"id": 430, "tag": "Steps_UHD_noL255"},
                6: {"id": 431, "tag": "Ramp_UHD_L255rm1"},
                7: {"id": 432, "tag": "Ramp_UHD_L255rm2"},
                8: {"id": 433, "tag": "Ramp_UHD_noL255"},
                9: {"id": 434, "tag": "Dolby Vision FHD"},
                10: {"id": 435, "tag": "CornerBox_FHD"},
                11: {"id": 436, "tag": "Checker_FHD"},
                12: {"id": 437, "tag": "Steps_FHD_L255rm1"},
                13: {"id": 438, "tag": "Steps_FHD_L255rm2"},
                14: {"id": 439, "tag": "Steps_FHD_noL255"},
                15: {"id": 440, "tag": "Ramp_FHD_L255rm1"},
                16: {"id": 441, "tag": "Ramp_FHD_L255rm2"},
                17: {"id": 442, "tag": "Ramp_FHD_noL255"},
            },
            "hd": {
                "tag": "HD",
                0: {"id": 350, "tag": "High Clipping"},
                1: {"id": 351, "tag": "Low Clipping"},
                2: {"id": 352, "tag": "Color Noise 01"},
                3: {"id": 353, "tag": "Color Noise 02"},
                4: {"id": 354, "tag": "Color Noise 04"},
                5: {"id": 355, "tag": "Color Noise 08"},
                6: {"id": 356, "tag": "Triangle"},
                7: {"id": 357, "tag": "Color Wipe Full"},
                8: {"id": 358, "tag": "Color Wipe Half"},
                9: {"id": 359, "tag": "Composite"},
                10: {"id": 360, "tag": "H Multiburst"},
                11: {"id": 361, "tag": "V Multiburst"},
                12: {"id": 362, "tag": "Checkers 02"},
                13: {"id": 363, "tag": "Checkers 04"},
                14: {"id": 364, "tag": "Checkers 08"},
                15: {"id": 365, "tag": "Checkers 16"},
                16: {"id": 366, "tag": "Checkers 32"},
                17: {"id": 367, "tag": "Checkers Log"},
                18: {"id": 368, "tag": "Many Circles"},
                19: {"id": 369, "tag": "Center Circle"},
                20: {"id": 370, "tag": "Many Squares"},
                21: {"id": 371, "tag": "Grid"},
                22: {"id": 372, "tag": "H Lines 02"},
                23: {"id": 373, "tag": "H Lines 04"},
                24: {"id": 374, "tag": "H Lines 08"},
                25: {"id": 375, "tag": "H Lines Log"},
                26: {"id": 376, "tag": "V Lines 02"},
                27: {"id": 377, "tag": "V Lines 04"},
                28: {"id": 378, "tag": "V Lines 08"},
                29: {"id": 380, "tag": "Geometry Points 02"},
                30: {"id": 381, "tag": "Geometry Points 04"},
                31: {"id": 382, "tag": "Geometry Points 08"},
                32: {"id": 383, "tag": "Geometry Points 16"},
                33: {"id": 384, "tag": "Geometry Points 32"},
                34: {"id": 385, "tag": "Geometry Squares 04"},
                35: {"id": 386, "tag": "Geometry Squares 08"},
                36: {"id": 387, "tag": "Geometry Squares 16"},
                37: {"id": 388, "tag": "Geometry Squares 32"},
                38: {"id": 389, "tag": "H Length"},
                39: {"id": 390, "tag": "V Length"},
                40: {"id": 391, "tag": "Overscan"},
                41: {"id": 392, "tag": "BW Evaluation 2"},
                42: {"id": 393, "tag": "BW Evaluation"},
                43: {"id": 394, "tag": "H Wedge"},
                44: {"id": 395, "tag": "Star Burst"},
                45: {"id": 396, "tag": "V Wedge"},
                46: {"id": 397, "tag": "RGB Text"},
            },
            "pva": {
                "tag": "PVA",
                0: {"id": 443, "tag": "(BT709) White_Clipping"},
                1: {"id": 444, "tag": "(BT709) Black_Clipping"},
                2: {"id": 445, "tag": "(BT709) APL_W_B_Clipping"},
                3: {"id": 446, "tag": "(BT709) Color_Clipping"},
                4: {"id": 447, "tag": "(BT709) Sharpness_Overscan"},
                5: {"id": 448, "tag": "(BT709) Alignment"},
                6: {"id": 449, "tag": "(BT709) Multi_Skin_Tone"},
                7: {"id": 450, "tag": "(BT709) Restaurant_Scene"},
                8: {"id": 451, "tag": "(BT709) Skin_Tone"},
                9: {"id": 579, "tag": "(BT2020) White_Clipping"},
                10: {"id": 580, "tag": "(BT2020) Black_Clipping"},
                11: {"id": 581, "tag": "(BT2020) APL_W_B_Clipping"},
                12: {"id": 582, "tag": "(BT2020) Color_Clipping"},
                13: {"id": 583, "tag": "(BT2020) Sharpness_Overscan"},
                14: {"id": 584, "tag": "(BT2020) Alignment"},
                15: {"id": 585, "tag": "(BT2020) Multi_Skin_Tone"},
                16: {"id": 586, "tag": "(BT2020) Restaurant_Scene"},
                17: {"id": 587, "tag": "(BT2020) Skin_Tone"},
            },
            "spe": {
                "tag": "SPE",
                0: {"id": 452, "tag": "(4:2:0) Girl"},
                1: {"id": 453, "tag": "(4:2:0) Women"},
                2: {"id": 454, "tag": "(4:2:0) Girl HDR & SDR"},
                3: {"id": 455, "tag": "(4:4:4 Full) Girl"},
                4: {"id": 588, "tag": "(4:4:4 Full) Women"},
                5: {"id": 589, "tag": "(4:4:4 Full) Girl HDR & SDR"},
                6: {"id": 590, "tag": "(4:4:4 Limit) Girl"},
                7: {"id": 591, "tag": "(4:4:4 Limit) Women"},
                8: {"id": 590, "tag": "(4:4:4 Limit) Girl HDR & SDR"},
            },
            "spears & munsil": {
                "tag": "SPEARS & MUNSIL",
                0: {"id": 456, "tag": "Bias_Light_10%"},
                1: {"id": 457, "tag": "Bias_Light_15%"},
                2: {"id": 458, "tag": "Framing"},
                3: {"id": 459, "tag": "Hammock_24p"},
                4: {"id": 460, "tag": "Hammock_30p"},
                5: {"id": 461, "tag": "Hammock_260i"},
                6: {"id": 462, "tag": "Mixed_video_H_60i"},
                7: {"id": 463, "tag": "Mixed_Video_V_60i"},
                8: {"id": 464, "tag": "ColorTint_01_Red"},
                9: {"id": 465, "tag": "ColorTint_01_Green"},
                10: {"id": 466, "tag": "ColorTint_01_Blue"},
                11: {"id": 467, "tag": "Jaggies_Full_60i"},
                12: {"id": 468, "tag": "Ship1_60i"},
                13: {"id": 469, "tag": "Ship2_60i"},
                14: {"id": 470, "tag": "Ship3_60i"},
            },
            "user (stills)": {
                "tag": "USER (STILLS)",
                0: {"id": 398, "tag": "User Pattern1 ()"},
                1: {"id": 399, "tag": "User Pattern2 ()"},
                2: {"id": 400, "tag": "User Pattern3 ()"},
                3: {"id": 401, "tag": "User Pattern4 ()"},
                4: {"id": 402, "tag": "User Pattern5 ()"},
                5: {"id": 403, "tag": "User Pattern6 ()"},
            },
            "ire window": {},
            "shortcuts": {
                "tag": "SHORTCUTS",
                0: {"id": 471, "tag": "SHORTCUTS 1"},
                1: {"id": 472, "tag": "SHORTCUTS 2"},
                2: {"id": 473, "tag": "SHORTCUTS 3"},
                3: {"id": 474, "tag": "SHORTCUTS 4"},
                4: {"id": 475, "tag": "SHORTCUTS 5"},
                5: {"id": 476, "tag": "SHORTCUTS 6"},
                6: {"id": 477, "tag": "SHORTCUTS 7"},
                7: {"id": 478, "tag": "SHORTCUTS 8"},
                8: {"id": 495, "tag": "SHORTCUTS 9"},
                9: {"id": 480, "tag": "SHORTCUTS 10"},
                10: {"id": 481, "tag": "SHORTCUTS 11"},
                11: {"id": 482, "tag": "SHORTCUTS 12"},
                12: {"id": 483, "tag": "SHORTCUTS 13"},
                13: {"id": 484, "tag": "SHORTCUTS 14"},
            },
        },
        "color space": {
            "tag": "COLOR SPACE",
            "function": "sendsingle",
            "category_type": 99,
            0: {"id": 0, "tag": "RGB(0-255)"},
            1: {"id": 1, "tag": "RGB(16-235)"},
            2: {"id": 2, "tag": "YC 4:4:4(16-235)"},
            3: {"id": 3, "tag": "YC 4:2:2(16-235)"},
            4: {"id": 4, "tag": "YC 4:2:0(16-235)"},
        },
        "bt 2020": {
            "tag": "BT 2020",
            "function": "sendsingle",
            "category_type": 112,
            0: {"id": 1, "tag": "ENABLE"},
            1: {"id": 0, "tag": "DISABLE"},
        },
        "color depth": {
            "tag": "COLOR DEPTH",
            "function": "sendsingle",
            "category_type": 100,
            0: {"id": 0, "tag": "8Bit"},
            1: {"id": 1, "tag": "10Bit"},
            2: {"id": 2, "tag": "12Bit"},
            3: {"id": 3, "tag": "16Bit"},
        },
        "hdcp": {
            "tag": "HDCP",
            "function": "sendsingle",
            "category_type": 101,
            0: {"id": 0, "tag": "HDCP OFF"},
            1: {"id": 1, "tag": "HDCP 1.4"},
            2: {"id": 2, "tag": "HDCP 2.2"},
            3: {"id": 3, "tag": "HDCP AUTO"},
        },
        "hdmi/dvi": {
            "tag": "HDMI/DVI",
            "function": "sendsingle",
            "category_type": 102,
            0: {"id": 0, "tag": "DVI"},
            1: {"id": 1, "tag": "HDMI"},
            2: {"id": 2, "tag": "AUTO"},
        },
        "hdr": {
            "tag": "HDR",
            "function": "sendsingle",
            "category_type": 111,
            0: {"id": 0, "tag": "HDR OFF(SDR)"},
            1: {"id": 1, "tag": "HDR-10"},
            2: {"id": 2, "tag": "HLG"},
            3: {"id": 3, "tag": "HDR CUSTOM 1"},
            4: {"id": 4, "tag": "HDR CUSTOM 2"},
            5: {"id": 5, "tag": "HDR CUSTOM 3"},
            6: {"id": 6, "tag": "HDR CUSTOM 4"},
            7: {"id": 7, "tag": "HDR CUSTOM 5"},
            8: {"id": 8, "tag": "HDR CUSTOM 6"},
            9: {"id": 9, "tag": "HDR CUSTOM 7"},
            10: {"id": 10, "tag": "HDR CUSTOM 8"},
            11: {},
        },
        "rgb triplet": {},
        "timing details": {},
    },
    "video tests": {
        "tag": "Video Tests",
        "function": "senddouble",
        "category_type": 98,
        0: {"id": 404, "tag": "Spicey Pixels Chongqing Day"},
        1: {"id": 405, "tag": "Spicey Pixels Chongqing Night"},
        2: {"id": 406, "tag": "Spicey Pixels Chongqing Lights"},
        3: {"id": 407, "tag": "Spicey Pixels Chongqing Cars"},
        4: {"id": 408, "tag": "Spicey Pixels Chongqing Cars2"},
        5: {"id": 411, "tag": "Spicey Pixels London Yogurt"},
        6: {"id": 412, "tag": "Spicey Pixels London River"},
        7: {"id": 413, "tag": "Spicey Pixels London Sidewalk"},
        8: {"id": 414, "tag": "Spicey Pixels London Busses"},
        9: {"id": 415, "tag": "Spicey Pixels London cafe"},
        10: {"id": 416, "tag": "Spicey Pixels Mukilteo Street"},
        11: {"id": 417, "tag": "Spicey Pixels Mukilteo Loading"},
        12: {"id": 418, "tag": "Spicey Pixels Carnival Wheel"},
        13: {"id": 419, "tag": "Spicey Pixels Carnival Ride"},
        14: {"id": 420, "tag": "Spicey Pixels Carnival night"},
        15: {"id": 421, "tag": "Spicey Pixels Carnival Balloon Pop"},
        16: {"id": 422, "tag": "Spicey Pixels Tiger Mountain 120"},
        17: {"id": 423, "tag": "Spicey Pixels Biker 120"},
        18: {"id": 424, "tag": "SPE Test Video"},
        19: {"id": 409, "tag": "User Video Clip 1"},
        20: {"id": 410, "tag": "User Video Clip 2"},
        21: {"id": 471, "tag": "Automation Testing Clip"},
    },
    "audio generator": {
        "tag": "Audio Generator",
        "pcm audio": {
            "tag": "PCM AUDIO",
            "audio sampling rate": {
                "tag": "Audio Sampling Rate",
                "function": "sendsingle",
                "category_type": 103,
                0: {"id": 0, "tag": "32K"},
                1: {"id": 1, "tag": "44.1K"},
                2: {"id": 2, "tag": "48K"},
                3: {"id": 3, "tag": "88K"},
                4: {"id": 4, "tag": "96K"},
                5: {"id": 5, "tag": "176k"},
                6: {"id": 6, "tag": "192k"},
            },
            "audio bit depth": {
                "tag": "Audio Bit Depth",
                "function": "sendsingle",
                "category_type": 104,
                0: {"id": 0, "tag": "16Bit"},
                1: {"id": 1, "tag": "20Bit"},
                2: {"id": 2, "tag": "24Bit"},
            },
            "sinewave tone": {
                "tag": "Sinewave Tone",
                "function": "sendsingle",
                "category_type": 115,
                0: {"id": 0, "tag": "SINEWAVE TONE(100Hz)"},
                1: {"id": 1, "tag": "SINEWAVE TONE(200Hz)"},
                2: {"id": 2, "tag": "SINEWAVE TONE(300Hz)"},
                3: {"id": 3, "tag": "SINEWAVE TONE(400Hz)"},
                4: {"id": 4, "tag": "SINEWAVE TONE(500Hz)"},
                5: {"id": 5, "tag": "SINEWAVE TONE(600Hz)"},
                6: {"id": 6, "tag": "SINEWAVE TONE(700Hz)"},
                7: {"id": 7, "tag": "SINEWAVE TONE(800Hz)"},
                8: {"id": 8, "tag": "SINEWAVE TONE(900Hz)"},
                9: {"id": 9, "tag": "SINEWAVE TONE(1KHz)"},
                10: {"id": 10, "tag": "SINEWAVE TONE(2KHz)"},
                11: {"id": 11, "tag": "SINEWAVE TONE(3KHz)"},
                12: {"id": 12, "tag": "SINEWAVE TONE(4KHz)"},
                13: {"id": 13, "tag": "SINEWAVE TONE(5KHz)"},
            },
            "audio volume": {
                "tag": "Audio Volume",
                "function": "sendsingle",
                "category_type": 109,
                0: {"id": 0, "tag": "-60db"},
                1: {"id": 1, "tag": "-54db"},
                2: {"id": 2, "tag": "-48db"},
                3: {"id": 3, "tag": "-42db"},
                4: {"id": 4, "tag": "-36db"},
                5: {"id": 5, "tag": "-30db"},
                6: {"id": 6, "tag": "-24db"},
                7: {"id": 7, "tag": "-18db"},
                8: {"id": 8, "tag": "-12"},
                9: {"id": 9, "tag": "-6db"},
                10: {"id": 10, "tag": "0db"},
            },
            "audio channel config": {
                "tag": "Audio Channel Config",
                "function": "sendsingle",
                "category_type": 107,
                0: {"id": 0, "tag": "2CH (FR_FL)"},
                1: {"id": 1, "tag": "2.1CH (LFE_FR_FL)"},
                2: {"id": 2, "tag": "3CH (FC_FR_FL)"},
                3: {"id": 3, "tag": "3.1CH (FC_LFE_FR_FL)"},
                4: {"id": 4, "tag": "3CH (RC_FR_FL)"},
                5: {"id": 5, "tag": "3.1CH (RC_LFE_FR_FL)"},
                6: {"id": 6, "tag": "4CH (RC_LFE_FR_FL)"},
                7: {"id": 7, "tag": "4.1CH (RC_FC_LFE_FR_FL)"},
                8: {"id": 8, "tag": "4CH (RR_RL_FR_FL)"},
                9: {"id": 9, "tag": "4.1CH (RR_RL_LFE_FR_FL)"},
                10: {"id": 10, "tag": "5CH (RR_RS_FC_FR_FL)"},
                11: {"id": 11, "tag": "5.1CH (RR_RL_FC_LFE_FR_FL)"},
                12: {"id": 12, "tag": "5CH (RC_RR_RL_FR_FL)"},
                13: {"id": 13, "tag": "5.1CH (RC_RR_RL_LFE_FR_FL)"},
                14: {"id": 14, "tag": "6CH (RC_RR_RL_FC_FR_FL)"},
                15: {"id": 15, "tag": "6.1CH (RC_RR_RL_FC_LFE_FR_FL)"},
                16: {"id": 16, "tag": "6CH (RRC_RLC_RR_RL_FR_FL)"},
                17: {"id": 17, "tag": "6.1CH (RRC_RLC_RR_RL_LFE_FR_FL)"},
                18: {"id": 18, "tag": "7CH (RRC_RLC_RR_RL_FC_FR_FL)"},
                19: {"id": 19, "tag": "7.1CH (RRC_RLC_RR_RL_FC_LFE_FR_FL)"},
                20: {"id": 20, "tag": "4CH (FRC_FLC_FR_FL)"},
                21: {"id": 21, "tag": "4.1CH (FRC_FLC_LFE_FR_FL)"},
                22: {"id": 22, "tag": "5CH (FRC_FLC_FC_FR_FL)"},
                23: {"id": 23, "tag": "5.1CH (FRC_FLC_FC_LFE_FR_FL)"},
                24: {"id": 24, "tag": "5CH (FRC_FLC_RC_FR_FL)"},
                25: {"id": 25, "tag": "5.1CH (FRC_FLC_RC_FC_FR_FL)"},
                26: {"id": 26, "tag": "6CH (FRC_FLC_RC_FC_FR_FL)"},
                27: {"id": 27, "tag": "6.1CH (FRC_FLC_RC_FC_LFE_FR_FL)"},
                28: {"id": 28, "tag": "6CH (FRC_FLC_RR_RL_FR_FL)"},
                29: {"id": 29, "tag": "6.1CH (FRC_FLC_RR_RL_LFE_FR_FL)"},
                30: {"id": 30, "tag": "7CH (FRC_FLC_RR_RL_FC_FR_FL)"},
                31: {"id": 31, "tag": "7.1CH (FRC_FLC_RR_RL_FC_LFE_FR_FL)"},
            },
        },
        "dolby audio generator": {
            "tag": "DOLBY AUDIO GENERATOR",
            "dolby digital": {
                "tag": "DOLBY Digital",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 2, "tag": "Dolby Digital-32KHz-2.0Ch"},
                1: {"id": 3, "tag": "Dolby Digital-32KHz-5.1Ch"},
                2: {"id": 4, "tag": "Dolby Digital-44.1KHz-2.0Ch"},
                3: {"id": 5, "tag": "Dolby Digital-44.1KHz-5.1Ch"},
                4: {"id": 6, "tag": "Dolby Digital-48KHz-2.0Ch"},
                5: {"id": 7, "tag": "Dolby Digital-48KHz-5.1Ch"},
            },
            "dolby digital plus": {
                "tag": "DOLBY Digital Plus",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 8, "tag": "Dolby Digital Plus-48KHz-2.0Ch"},
                1: {"id": 9, "tag": "Dolby Digital Plus-48KHz-5.1Ch"},
                2: {"id": 10, "tag": "Dolby Digital Plus-48KHz-7.1Ch"},
                3: {"id": 11, "tag": "Dolby Digital Plus-48KHz-Atmos"},
            },
            "dolby mat": {
                "tag": "DOLBY MAT",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 12, "tag": "Dolby MAT(PCM)-44.1KHz-2.0Ch"},
                1: {"id": 13, "tag": "Dolby MAT(PCM)-44.1KHz-5.1Ch"},
                2: {"id": 14, "tag": "Dolby MAT(PCM)-44.1KHz-7.1Ch"},
                3: {"id": 15, "tag": "Dolby MAT(PCM)-48KHz-2.0Ch"},
                4: {"id": 16, "tag": "Dolby MAT(PCM)-48KHz-5.1Ch"},
                5: {"id": 17, "tag": "Dolby MAT(PCM)-48KHz-7.1Ch"},
                6: {"id": 18, "tag": "Dolby MAT(PCM object audio)-44.1KHz-Dolby Atmos"},
                7: {"id": 19, "tag": "Dolby MAT(PCM object audio)-48KHz-Dolby Atmos"},
            },
            "dolby truehd": {
                "tag": "DOLBY MAT (DOLBY TrueHD)",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 20, "tag": "Dolby MAT(Dolby TrueHD)-48KHz-2.0Ch"},
                1: {"id": 21, "tag": "Dolby MAT(Dolby TrueHD)-48KHz-5.1Ch"},
                2: {"id": 22, "tag": "Dolby MAT(Dolby TrueHD)-48KHz-7.1Ch"},
                3: {"id": 23, "tag": "Dolby MAT(Dolby TrueHD)-96KHz-2.0Ch"},
                4: {"id": 24, "tag": "Dolby MAT(Dolby TrueHD)-96KHz-5.1Ch"},
                5: {"id": 25, "tag": "Dolby MAT(Dolby TrueHD)-96KHz-7.1Ch"},
                6: {"id": 26, "tag": "Dolby MAT(Dolby TrueHD)-192KHz-2.0Ch"},
                7: {"id": 27, "tag": "Dolby MAT(Dolby TrueHD)-192KHz-5.1Ch"},
                8: {
                    "id": 28,
                    "tag": "Dolby MAT(Dolby TrueHD)Object Based 48KHz-Dolby Atmos",
                },
            },
            "my streams": {
                "tag": "My Streams",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 288, "tag": "MY STREAM1 ()"},
                1: {"id": 308, "tag": "MY STREAM2 ()"},
                2: {"id": 328, "tag": "MY STREAM3 ()"},
                3: {"id": 348, "tag": "MY STREAM4 ()"},
                4: {"id": 368, "tag": "MY STREAM5 ()"},
                5: {"id": 388, "tag": "MY STREAM6 ()"},
            },
        },
        "ext.analog input": {
            "tag": "EXT.ANALOG L/R INPUT",
            "function": "senddouble",
            "category_type": 105,
            0: {"id": 0, "tag": "ENABLE"},
        },
        "dts audio generator": {
            "tag": "DTS AUDIO GENERATOR",
            "dts digital surround": {
                "tag": "DTS Digital Surround",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 562, "tag": "DTS Digital Surround-48KHz-2.0Ch"},
                1: {"id": 563, "tag": "DTS Digital Surround-48KHz-5.1Ch"},
                2: {"id": 564, "tag": "DTS Digital Surround-48.1KHz-6.1Ch"},
                3: {"id": 565, "tag": "DTS Digital Surround-44.1KHz-5.1Ch"},
                4: {"id": 566, "tag": "DTS Digital Surround-96KHz-5.1Ch"},
            },
            "dts-hd high resolution": {
                "tag": "DTS-HD Higher Resolution",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 567, "tag": "DTS-HD High Resolution-48KHz-5.1Ch"},
                1: {"id": 568, "tag": "DTS-HD High Resolution-48KHz-7.1Ch"},
                2: {"id": 569, "tag": "DTS-HD High Resolution-96KHz-7.1Ch"},
                3: {"id": 570, "tag": "DTS-HD High Resolution-88.2KHz-7.1Ch"},
            },
            "dts-hd master audio": {
                "tag": "DTS-HD Master Audio",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 571, "tag": "DTS-HD Master Audio-48KHz-5.1Ch"},
                1: {"id": 572, "tag": "DTS-HD Master Audio-48KHz-7.1Ch"},
                2: {"id": 573, "tag": "DTS-HD Master Audio-192KHz-2.0Ch"},
                3: {"id": 574, "tag": "DTS-HD Master Audio-192KHz-7.1Ch"},
            },
            "dts x": {
                "tag": "DTS: X",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 575, "tag": "DTS:X-48KHz-7.1.4Ch"},
                1: {"id": 576, "tag": "DTS:X-48KHz-5.1.4Ch"},
                2: {"id": 577, "tag": "DTS:X Master Audio-48KHz-7.1.4Ch"},
                3: {"id": 578, "tag": "DTS:X Master Audio-96KHz-7.1.4Ch"},
                4: {"id": 579, "tag": "DTS:X(32 Objects)"},
            },
            "dts express": {
                "tag": "DTS Express",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 580, "tag": "DTS Low Bit Rate-48KHz-5.1Ch"},
            },
            "my streams": {
                "tag": "MY STREAMS",
                "function": "senddouble",
                "category_type": 105,
                0: {"id": 581, "tag": "MY STREAM1 ()"},
                1: {"id": 601, "tag": "MY STREAM2 ()"},
                2: {"id": 621, "tag": "MY STREAM3 ()"},
                3: {"id": 641, "tag": "MY STREAM4 ()"},
                4: {"id": 661, "tag": "MY STREAM5 ()"},
                5: {"id": 681, "tag": "MY STREAM6 ()"},
            },
        },
    },
    "audio tests": {
        "tag": "Audio Tests",
        "sync-latency test": {
            "tag": "SYNC-LATENCY TEST",
            "video settings": {
                "tag": "VIDEO SETTINGS",
                "function": "sendsingle",
                "category_type": 119,
                0: {"id": 0, "tag": "3840X2160 30HZ"},
                1: {"id": 1, "tag": "3840X2160 29.97HZ"},
                2: {"id": 2, "tag": "3840X2160 25HZ"},
                3: {"id": 3, "tag": "3840X2160 24HZ"},
                4: {"id": 4, "tag": "3840X2160 60HZ"},
                5: {"id": 5, "tag": "3840X2160 59.94HZ"},
                6: {"id": 6, "tag": "3840X2160 50HZ"},
                7: {"id": 7, "tag": "1080P 30HZ"},
                8: {"id": 8, "tag": "1080P 29.97HZ"},
                9: {"id": 9, "tag": "1080P 25HZ"},
                10: {"id": 10, "tag": "1080P 24HZ"},
                11: {"id": 11, "tag": "1080P 60HZ"},
                12: {"id": 12, "tag": "1080P 59.94HZ"},
                13: {"id": 13, "tag": "1080P 50HZ"},
                14: {"id": 14, "tag": "1080P 120HZ"},
                15: {"id": 15, "tag": "1080P 119.88HZ"},
            },
            "dolby vision settings": {
                "tag": "DOLBY VISION SETTINGS",
                "function": "sendsingle",
                "category_type": 135,
                0: {"id": 0, "tag": "DOLBY VISION OFF"},
                1: {"id": 1, "tag": "DOLBY VISION SINK-LED"},
                2: {"id": 2, "tag": "DOLBY VISION SOURCE-LED"},
            },
            "audio stream adjust": {
                "tag": "AUDIO STREAM ADJUST",
                "function": "senddouble",
                "category_type": 118,
                0: {"id": None, "tag": "Adjust audio -500ms to +500ms"},
            },
            "av sensors functional test": {
                "tag": "AV SENSORS FUNCTIONAL TEST",
                "function": "sendsingle",
                "category_type": 136,
                0: {"id": 0, "tag": "Mic Functional Test - READ STATUS"},
                1: {"id": 1, "tag": "Visual Sensor Test - READ STATUS"},
            },
            "arm av latency": {
                "tag": "ARM AV LATENCY",
                "function": "sendsingle",
                "category_type": 131,
                0: {},
            },
            "arm ARC latency": {
                "tag": "ARM ARC LATENCY",
                "function": "sendsingle",
                "category_type": 131,
                0: {},
            },
            "arm eARC latency": {
                "tag": "ARM eARC LATENCY",
                "function": "sendsingle",
                "category_type": 131,
                0: {},
            },
        },
        "source-speaker test": {
            "tag": "SOURCE-SPEAKER TEST",
            "function": "senddouble",
            "category_type": 105,
            0: {"id": 528, "tag": "SPEAKER ALLOCATION"},
            1: {"id": 538, "tag": "WHITE NOISE"},
            2: {"id": 548, "tag": "SWEEP AUDIO"},
        },
    },
    "edid earc cds": {
        "tag": "EDID eARC CDS",
        "sink device edid info": {
            "tag": "SINK DEVICE EDID INFO",
            "function": "sendsingle",
            "category_type": 47160,
            0: {"id": 1, "tag": "READ EDID"},
            1: {"id": None, "tag": "SAVE EDID"},
            2: {"id": None, "tag": "OPEN EDID"},
        },
        "earc/arc audio info": {
            "tag": "eARC/ARC AUDIO INFO",
            "function": "sendother",
            "category_type": None,
        },
        "arc hpd ctl": {
            "tag": "ARC HPD CTL",
            "function": "sendsingle",
            "category_type": 177,
            0: {"id": 1, "tag": "ASSERT HPD(HIGH)"},
            1: {"id": 0, "tag": "DEASSERT HPD(LOW)"},
        },
        "arc physical hpd ctl": {
            "tag": "ARC PHYSICAL HPD CTL",
            "function": "sendsingle",
            "category_type": 177,
            0: {"id": 1, "tag": "ASSERT HPD(HIGH)"},
            1: {"id": 0, "tag": "DEASSERT HPD(LOW)"},
        },
        "earc hpd bit ctl": {
            "tag": "eARC HPD bit CTL",
            "function": "sendsingle",
            "category_type": 178,
            0: {"id": 1, "tag": "SET HDMI_HPD bit(=1)"},
            1: {"id": 0, "tag": "CLERA HDMI_HPD bit(=0)"},
        },
        "hdmi +5v power ctl": {
            "tag": "HDMI +5V POWER CTL",
            "function": "sendsingle",
            "category_type": 179,
            0: {"id": 1, "tag": "SET HDMI TX +5V ON"},
            1: {"id": 0, "tag": "SET HDMI TX +5V OFF"},
        },
        "earc tx latency": {
            "tag": "eARC TX LATENCY",
            "function": "sendsingle",
            "category_type": 121,
            0: {"id": None, "tag": "ERX_LATENCY_REQ(To eARC RX) id=ms"},
        },
        "earc rx latency": {
            "tag": "eARC RX LATENCY",
            "function": "sendsingle",
            "category_type": 122,
            0: {"id": None, "tag": "ERX_LATENCY_REQ(To eARC TX) id=ms"},
        },
        "send cec command": {
            "tag": "Send CEC Command",
            "function": "sendsingle",
            "category_type": 122,
            0: {},
        },
    },
    "system setup": {
        "tag": "System Setup",
        "ip management": {"tag": "IP MANAGEMENT"},
        "arc/earc out setup": {
            "tag": "ARC/eARC OUT SETUP",
            "function": "sendsingle",
            "category_type": 131,
            0: {"id": 0, "tag": "DISABLE ARC/eARC"},
            1: {"id": 1, "tag": "ENABLE eARC"},
            2: {"id": 2, "tag": "ENABLE ARC"},
        },
        "vitals": {
            "tag": "VITALS",
            "function": "sendsingle",
            "category_type": 63577,
            "id": 1,
        },
        "fan control": {
            "tag": "FAN CONTROL",
            "function": "sendsingle",
            "category_type": 30723,
            0: {"id": 0, "tag": "OFF"},
            1: {"id": 1, "tag": "LOW SPEED"},
            2: {"id": 2, "tag": "MIDDLE SPEED"},
            3: {"id": 3, "tag": "HIGH SPEED"},
        },
        "reset all settings": {
            "tag": "RESET ALL SETTINGS",
            "reset default": {
                "function": "sendother",
                "category_type": 30722,
                "id": None,
            },
        },
        "tools": {
            "tag": "Tools",
            "function": "sendother",
            "category_type": 65025,
            "id": None,
        },
        "update firmware": {
            "tag": "UPDATE FIRMWARE",
            "update firmware": {"tag": "Update Firmware"},
            "reboot": {"tag": "reboot"},
        },
    },
}
